Instructors
sudhaneupane/nninebackend pull request #15
Opened 2024-09-02 05:37 UTC by madhavbanjade

Instructors API Done...

2024-09-02 09:29 UTC, Mingtindu requested changes

2024-09-02 09:29 UTC, Mingtindu commented on models/instructor.model.js
> +  {
Add id field

2024-09-02 09:29 UTC, Mingtindu commented on src/controllers/instructor.controller.js
> +
add one block of code to check if the instructor is already exist or not 
user will be able to create instructor only if it is  not exist in the database

2024-09-02 09:29 UTC, Mingtindu commented on src/controllers/instructor.controller.js
> +  // console.log(id);
remove comment

2024-09-02 09:29 UTC, Mingtindu commented on src/controllers/instructor.controller.js
> +      .status(200)
change status to 201

2024-09-04 05:09 UTC, Mingtindu approved these changes

2024-09-04 07:27 UTC, merged

2024-09-04 07:28 UTC, madhavbanjade commented
instructors and schedules